# File: .github/workflows/repo-sync.yml
name: merge-from-passerby
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ passerby-b ]
  repository_dispatch:
    types: passerby-b
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: sync passerby-b-JDDJ
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/passerby-b/JDDJ.git"
          source_branch: "main"
          destination_branch: "passerby-b"
          github_token: ${{ secrets.PAT }}

      - name: Merge main from passerby-b
        uses: devmasx/merge-branch@v1.3.1
        if: env.PAT
        with:
          type: now
          from_branch: passerby-b
          target_branch: jddj
          github_token: ${{ secrets.PAT }}
